### ISSUE TITLE
bug:not working with react 

### ISSUE THREAD

**Issue by Eko450-eng** [PassTheMayo/minecraft-server-util#58]
The npm package doesn't seem to be working with react, as soon as you import the package (Either way with import or require) you get "TypeError: util_1.TextEncoder is not a constructor"

**Full error log: 
  3 | function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
  4 | return new (P || (P = Promise))(function (resolve, reject) {
  5 |     function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
> 6 |     function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
    | ^  7 |     function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
  8 |     step((generator = generator.apply(thisArg, _arguments || [])).next());
  9 | });
**
```javascript
Please put any code related to the issue within these backticks
```

**Comment by PassTheMayo** [comment]
This library does not have any support with the client side browser, so using this in a React environment will not work. If you are using something like NextJS, you *might* be able to use the status method within the `getServerSideProps` function for a page component since that is ran on the server, but no promises on that.
