### ISSUE TITLE
Update protocol methods table in documentation

### ISSUE THREAD

**Issue by mve** [PassTheMayo/minecraft-server-util#64]
https://passthemayo.gitbook.io/minecraft-server-util/api/java-server-status#protocol-methods
This table is missing the statusLegacy request and should maybe have the deprecated requests removed?

Also i couldn't find if the documentation was open source, perhaps a good idea to open source it so contributors can more easily suggest / help with changes.

**Comment by PassTheMayo** [comment]
I was gonna add it to the documentation earlier but I had trouble with GitBook but I was able to add it now. The other status methods will remain deprecated in favor of `statusLegacy()` since this method has support for all previous versions without knowing which specific protocol version it is.

I've made the documentation open source at https://github.com/PassTheMayo/minecraft-server-util-docs.
