### ISSUE TITLE
maintenance plugin integration

### ISSUE THREAD

**Issue by Timong-craft** [PassTheMayo/minecraft-server-util#77]
Can you impement the https://www.spigotmc.org/resources/maintenance-bungee-and-spigot-support.40699 plugin that if this is enabled the status is maintenance or better the "Version" which you can set in the plugin like "offline" or "in maintenance".

**Comment by PassTheMayo** [comment]
This server plugin looks like it just modifies the MOTD and version information in the status packet to show that the server is offline. Since these messages are configurable by the server admin, there is no clear indicator to check if the server is actually in maintenance mode. This is also such a niche status that this wouldn’t be worth implementing for developers.
